export const statsPokemon = {
  hp: "Hp",
  attack: "Ataque",
  defense: "Defensa",
  specialattack: "Ataque Especial",
  specialdefense: "Defensa Especial",
  speed: "Velocidad",
};

export const typesPokemon = {
  electric: "electrico",
  normal: "normal",
  fire: "fuego",
  water: "agua",
  ice: "hielo",
  rock: "roca",
  flying: "volador",
  grass: "hierba",
  psychic: "psíquico",
  ghost: "psíquico",
  bug: "bicho",
  poison: "veneno",
  ground: "tierra",
  dragon: "dragón",
  steel: "acero",
  fighting: "lucha",
  default: "defecto",
  fairy: "hada",
  dark: "oscuro",
};
